amqp:
  url: 'amqp://guest:guest@localhost/'
debug: true
gates:
  gate_test_1:
    module: traccar_new
    amqp_url: 'amqp://guest:guest@localhost/'
    port: 8000
    exchange: ''
    routing_key: test_queue
databases:
  db_backend_test_1:
    module: adbapi
    amqp_url: 'amqp://guest:guest@localhost/'
    listen_queue: test_db_queue
    engine: pymysql
    database: tracker
    user: root
api:
  web_api_test_1:
    module: http
    amqp_url: 'amqp://guest:guest@localhost/'
    port: 8080
    exchange: ''
    routing_key: test_db_queue
    amqp_connections: 1
